### ISSUE TITLE
Centipede Vflip option

### ISSUE THREAD

**Issue by BabaYaga326** [MiSTer-devel/Arcade-Centipede_MiSTer#17]
I'm using a vertical monitor with my MiSTercade. The current horizontal orientation option flips Centipede upside down. Would it be possible to add a vertical flip option that rotates to orientate the game right side up to this core?

**Comment by JaguarLV** [comment]
Latest version has vertical flip.

**Comment by Toryalai1** [comment]
This is implemented and thus ticket can be closed
