### ISSUE TITLE
Request for Trackball support

### ISSUE THREAD

**Issue by BabaYaga326** [MiSTer-devel/Arcade-Centipede_MiSTer#18]
I’m looking for trackball support for the Centipede core. Thx!

**Comment by JimmyStones** [comment]
Do you know what kind of input your trackball is registering as on MiSTer (if not, please use the input test core and check the advanced mode, you'll be able to see there how it is coming through)?  Centipede supports mouse control already, which is what I'd expect trackballs to present as.

**Comment by BabaYaga326** [comment]
Trackball is working in test today. Thanks.

Now I just need the ability to rotate 180 degrees. The game is upside down on my vertical monitor.

**Comment by ghost** [comment]
> 
> Now I just need the ability to rotate 180 degrees. The game is upside down on my vertical monitor.

This is a separate issue. 
Since trackball is working, this ticket can be closed
