### ISSUE TITLE
Lots of noise coming through audio

### ISSUE THREAD

**Issue by berlonce** [MiSTer-devel/Arcade-Centipede_MiSTer#20]
Sounds like a bad feedback loop. Can hear game sounds faintly behind the noise, but I basically have to turn volume all the way down to play the game as the noise is so loud and distracting. Only happens on Centipede (Rev 3 and 4) AFAIK.

**Comment by JimmyStones** [comment]
My fault, a bad update - I've prepared a fix which is waiting for the PR to be tested and approved
